package com.swingnosefrog.solitaire.steamworks

import com.codedisaster.steamworks.SteamController
import com.swingnosefrog.solitaire.fonts.PromptFontConsts
import com.swingnosefrog.solitaire.inputmanager.IActionInputGlyph
import java.util.concurrent.ConcurrentHashMap

private val actionOriginToGlyph: MutableMap<SteamController.ActionOrigin, SteamActionInputGlyph> = ConcurrentHashMap()

/**
 * Returns cached instance of [IActionInputGlyph].
 */
fun SteamController.ActionOrigin.getActionInputGlyph(): SteamActionInputGlyph {
    return actionOriginToGlyph.getOrPut(this) { this.toSteamActionInputGlyph() }
}

private fun SteamController.ActionOrigin.toSteamActionInputGlyph(): SteamActionInputGlyph {
    val promptFontText: String = when (this) {
        SteamController.ActionOrigin.None -> " "
        SteamController.ActionOrigin.A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.LeftBumper ->  PromptFontConsts.XBOX_LEFT_SHOULDER
        SteamController.ActionOrigin.RightBumper -> PromptFontConsts.XBOX_RIGHT_SHOULDER
        SteamController.ActionOrigin.LeftGrip -> PromptFontConsts.GAMEPAD_L4
        SteamController.ActionOrigin.RightGrip -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.Start -> PromptFontConsts.GAMEPAD_START
        SteamController.ActionOrigin.Back -> PromptFontConsts.GAMEPAD_SELECT
        SteamController.ActionOrigin.LeftPad_Touch -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.LeftPad_Swipe -> PromptFontConsts.TRACKPAD_L_ANY
        SteamController.ActionOrigin.LeftPad_Click -> PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.LeftPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.LeftPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.LeftPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.LeftPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.RightPad_Touch -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.RightPad_Swipe -> PromptFontConsts.TRACKPAD_R_ANY
        SteamController.ActionOrigin.RightPad_Click -> PromptFontConsts.TRACKPAD_R_CLICK
        SteamController.ActionOrigin.RightPad_DPadNorth -> PromptFontConsts.TRACKPAD_R_UP
        SteamController.ActionOrigin.RightPad_DPadSouth -> PromptFontConsts.TRACKPAD_R_DOWN
        SteamController.ActionOrigin.RightPad_DPadWest ->  PromptFontConsts.TRACKPAD_R_LEFT
        SteamController.ActionOrigin.RightPad_DPadEast ->  PromptFontConsts.TRACKPAD_R_RIGHT
        SteamController.ActionOrigin.LeftTrigger_Pull ->   PromptFontConsts.XBOX_LEFT_TRIGGER_PULL
        SteamController.ActionOrigin.LeftTrigger_Click ->  PromptFontConsts.XBOX_LEFT_TRIGGER
        SteamController.ActionOrigin.RightTrigger_Pull ->  PromptFontConsts.XBOX_RIGHT_TRIGGER_PULL
        SteamController.ActionOrigin.RightTrigger_Click -> PromptFontConsts.XBOX_RIGHT_TRIGGER
        SteamController.ActionOrigin.LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.LeftStick_Click -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.Gyro_Move -> "Gyro"
        SteamController.ActionOrigin.Gyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.Gyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.Gyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.PS4_X -> PromptFontConsts.SONY_A
        SteamController.ActionOrigin.PS4_Circle -> PromptFontConsts.SONY_B
        SteamController.ActionOrigin.PS4_Triangle -> PromptFontConsts.SONY_Y
        SteamController.ActionOrigin.PS4_Square -> PromptFontConsts.SONY_X
        SteamController.ActionOrigin.PS4_LeftBumper -> PromptFontConsts.SONY_LEFT_SHOULDER
        SteamController.ActionOrigin.PS4_RightBumper -> PromptFontConsts.SONY_RIGHT_SHOULDER
        SteamController.ActionOrigin.PS4_Options -> PromptFontConsts.SONY_OPTIONS
        SteamController.ActionOrigin.PS4_Share -> PromptFontConsts.SONY_SHARE
        SteamController.ActionOrigin.PS4_LeftPad_Touch -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.PS4_LeftPad_Swipe -> PromptFontConsts.TRACKPAD_L_ANY
        SteamController.ActionOrigin.PS4_LeftPad_Click -> PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.PS4_LeftPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.PS4_LeftPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.PS4_LeftPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.PS4_LeftPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.PS4_RightPad_Touch -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.PS4_RightPad_Swipe -> PromptFontConsts.TRACKPAD_R_ANY
        SteamController.ActionOrigin.PS4_RightPad_Click -> PromptFontConsts.TRACKPAD_R_CLICK
        SteamController.ActionOrigin.PS4_RightPad_DPadNorth -> PromptFontConsts.TRACKPAD_R_UP
        SteamController.ActionOrigin.PS4_RightPad_DPadSouth -> PromptFontConsts.TRACKPAD_R_DOWN
        SteamController.ActionOrigin.PS4_RightPad_DPadWest ->  PromptFontConsts.TRACKPAD_R_LEFT
        SteamController.ActionOrigin.PS4_RightPad_DPadEast ->  PromptFontConsts.TRACKPAD_R_RIGHT
        SteamController.ActionOrigin.PS4_CenterPad_Touch -> PromptFontConsts.SONY_TOUCHPAD
        SteamController.ActionOrigin.PS4_CenterPad_Swipe -> PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.MOUSE_ANY
        SteamController.ActionOrigin.PS4_CenterPad_Click -> PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.BUTTON_PRESS
        SteamController.ActionOrigin.PS4_CenterPad_DPadNorth -> PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_UP
        SteamController.ActionOrigin.PS4_CenterPad_DPadSouth -> PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_DOWN
        SteamController.ActionOrigin.PS4_CenterPad_DPadWest ->  PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_LEFT
        SteamController.ActionOrigin.PS4_CenterPad_DPadEast ->  PromptFontConsts.SONY_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_RIGHT
        SteamController.ActionOrigin.PS4_LeftTrigger_Pull -> PromptFontConsts.SONY_LEFT_TRIGGER
        SteamController.ActionOrigin.PS4_LeftTrigger_Click -> PromptFontConsts.SONY_LEFT_TRIGGER
        SteamController.ActionOrigin.PS4_RightTrigger_Pull -> PromptFontConsts.SONY_RIGHT_TRIGGER
        SteamController.ActionOrigin.PS4_RightTrigger_Click -> PromptFontConsts.SONY_RIGHT_TRIGGER
        SteamController.ActionOrigin.PS4_LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.PS4_LeftStick_Click -> PromptFontConsts.SONY_LEFT_STICK
        SteamController.ActionOrigin.PS4_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.PS4_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.PS4_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.PS4_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.PS4_RightStick_Move ->  PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.PS4_RightStick_Click -> PromptFontConsts.SONY_RIGHT_STICK
        SteamController.ActionOrigin.PS4_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.PS4_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.PS4_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.PS4_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.PS4_DPad_North -> PromptFontConsts.DPAD_UP
        SteamController.ActionOrigin.PS4_DPad_South -> PromptFontConsts.DPAD_DOWN
        SteamController.ActionOrigin.PS4_DPad_West -> PromptFontConsts.DPAD_LEFT
        SteamController.ActionOrigin.PS4_DPad_East -> PromptFontConsts.DPAD_RIGHT
        SteamController.ActionOrigin.PS4_Gyro_Move -> "Gyro"
        SteamController.ActionOrigin.PS4_Gyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.PS4_Gyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.PS4_Gyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.XBoxOne_A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.XBoxOne_B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.XBoxOne_X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.XBoxOne_Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.XBoxOne_LeftBumper ->  PromptFontConsts.XBOX_LEFT_SHOULDER
        SteamController.ActionOrigin.XBoxOne_RightBumper -> PromptFontConsts.XBOX_RIGHT_SHOULDER
        SteamController.ActionOrigin.XBoxOne_Menu -> PromptFontConsts.XBOX_MENU
        SteamController.ActionOrigin.XBoxOne_View -> PromptFontConsts.XBOX_VIEW
        SteamController.ActionOrigin.XBoxOne_LeftTrigger_Pull ->  PromptFontConsts.XBOX_LEFT_TRIGGER_PULL
        SteamController.ActionOrigin.XBoxOne_LeftTrigger_Click -> PromptFontConsts.XBOX_LEFT_TRIGGER
        SteamController.ActionOrigin.XBoxOne_RightTrigger_Pull ->  PromptFontConsts.XBOX_RIGHT_TRIGGER_PULL
        SteamController.ActionOrigin.XBoxOne_RightTrigger_Click -> PromptFontConsts.XBOX_RIGHT_TRIGGER
        SteamController.ActionOrigin.XBoxOne_LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.XBoxOne_LeftStick_Click -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.XBoxOne_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.XBoxOne_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.XBoxOne_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.XBoxOne_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.XBoxOne_RightStick_Move ->  PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.XBoxOne_RightStick_Click -> PromptFontConsts.ANALOG_R_CLICK
        SteamController.ActionOrigin.XBoxOne_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.XBoxOne_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.XBoxOne_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.XBoxOne_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.XBoxOne_DPad_North -> PromptFontConsts.XBOX_DPAD_UP
        SteamController.ActionOrigin.XBoxOne_DPad_South -> PromptFontConsts.XBOX_DPAD_DOWN
        SteamController.ActionOrigin.XBoxOne_DPad_West ->  PromptFontConsts.XBOX_DPAD_LEFT
        SteamController.ActionOrigin.XBoxOne_DPad_East ->  PromptFontConsts.XBOX_DPAD_RIGHT
        SteamController.ActionOrigin.XBox360_A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.XBox360_B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.XBox360_X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.XBox360_Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.XBox360_LeftBumper ->  PromptFontConsts.XBOX_LEFT_SHOULDER
        SteamController.ActionOrigin.XBox360_RightBumper -> PromptFontConsts.XBOX_RIGHT_SHOULDER
        SteamController.ActionOrigin.XBox360_Start -> PromptFontConsts.GAMEPAD_START
        SteamController.ActionOrigin.XBox360_Back -> PromptFontConsts.GAMEPAD_SELECT
        SteamController.ActionOrigin.XBox360_LeftTrigger_Pull ->  PromptFontConsts.XBOX_LEFT_TRIGGER_PULL
        SteamController.ActionOrigin.XBox360_LeftTrigger_Click -> PromptFontConsts.XBOX_LEFT_TRIGGER
        SteamController.ActionOrigin.XBox360_RightTrigger_Pull ->  PromptFontConsts.XBOX_RIGHT_TRIGGER_PULL
        SteamController.ActionOrigin.XBox360_RightTrigger_Click -> PromptFontConsts.XBOX_RIGHT_TRIGGER
        SteamController.ActionOrigin.XBox360_LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.XBox360_LeftStick_Click -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.XBox360_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.XBox360_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.XBox360_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.XBox360_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.XBox360_RightStick_Move ->  PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.XBox360_RightStick_Click -> PromptFontConsts.ANALOG_R_CLICK
        SteamController.ActionOrigin.XBox360_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.XBox360_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.XBox360_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.XBox360_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.XBox360_DPad_North -> PromptFontConsts.XBOX_DPAD_UP
        SteamController.ActionOrigin.XBox360_DPad_South -> PromptFontConsts.XBOX_DPAD_DOWN
        SteamController.ActionOrigin.XBox360_DPad_West ->  PromptFontConsts.XBOX_DPAD_LEFT
        SteamController.ActionOrigin.XBox360_DPad_East ->  PromptFontConsts.XBOX_DPAD_RIGHT
        SteamController.ActionOrigin.SteamV2_A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.SteamV2_B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.SteamV2_X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.SteamV2_Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.SteamV2_LeftBumper ->  PromptFontConsts.XBOX_LEFT_SHOULDER
        SteamController.ActionOrigin.SteamV2_RightBumper -> PromptFontConsts.XBOX_RIGHT_SHOULDER
        SteamController.ActionOrigin.SteamV2_LeftGrip_Lower -> PromptFontConsts.GAMEPAD_L5
        SteamController.ActionOrigin.SteamV2_LeftGrip_Upper -> PromptFontConsts.GAMEPAD_L4
        SteamController.ActionOrigin.SteamV2_RightGrip_Lower -> PromptFontConsts.GAMEPAD_R5
        SteamController.ActionOrigin.SteamV2_RightGrip_Upper -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.SteamV2_LeftBumper_Pressure ->  PromptFontConsts.XBOX_LEFT_SHOULDER
        SteamController.ActionOrigin.SteamV2_RightBumper_Pressure -> PromptFontConsts.XBOX_RIGHT_SHOULDER
        SteamController.ActionOrigin.SteamV2_LeftGrip_Pressure ->  PromptFontConsts.GAMEPAD_L5
        SteamController.ActionOrigin.SteamV2_RightGrip_Pressure -> PromptFontConsts.GAMEPAD_R5
        SteamController.ActionOrigin.SteamV2_LeftGrip_Upper_Pressure -> PromptFontConsts.GAMEPAD_L4
        SteamController.ActionOrigin.SteamV2_RightGrip_Upper_Pressure -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.SteamV2_Start -> PromptFontConsts.GAMEPAD_START
        SteamController.ActionOrigin.SteamV2_Back -> PromptFontConsts.GAMEPAD_SELECT
        SteamController.ActionOrigin.SteamV2_LeftPad_Touch -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.SteamV2_LeftPad_Swipe -> PromptFontConsts.TRACKPAD_L_ANY
        SteamController.ActionOrigin.SteamV2_LeftPad_Click -> PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.SteamV2_LeftPad_Pressure -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.SteamV2_LeftPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.SteamV2_LeftPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.SteamV2_LeftPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.SteamV2_LeftPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.SteamV2_RightPad_Touch -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.SteamV2_RightPad_Swipe -> PromptFontConsts.TRACKPAD_R_ANY
        SteamController.ActionOrigin.SteamV2_RightPad_Click -> PromptFontConsts.TRACKPAD_R_CLICK
        SteamController.ActionOrigin.SteamV2_RightPad_Pressure -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.SteamV2_RightPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.SteamV2_RightPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.SteamV2_RightPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.SteamV2_RightPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.SteamV2_LeftTrigger_Pull ->   PromptFontConsts.XBOX_LEFT_TRIGGER_PULL
        SteamController.ActionOrigin.SteamV2_LeftTrigger_Click ->  PromptFontConsts.XBOX_LEFT_TRIGGER
        SteamController.ActionOrigin.SteamV2_RightTrigger_Pull ->  PromptFontConsts.XBOX_RIGHT_TRIGGER_PULL
        SteamController.ActionOrigin.SteamV2_RightTrigger_Click -> PromptFontConsts.XBOX_RIGHT_TRIGGER
        SteamController.ActionOrigin.SteamV2_LeftStick_Move -> PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.SteamV2_LeftStick_Click -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.SteamV2_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.SteamV2_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.SteamV2_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.SteamV2_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.SteamV2_Gyro_Move -> "Gyro"
        SteamController.ActionOrigin.SteamV2_Gyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.SteamV2_Gyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.SteamV2_Gyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.Switch_A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.Switch_B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.Switch_X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.Switch_Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.Switch_LeftBumper -> PromptFontConsts.NINTENDO_LEFT_SHOULDER
        SteamController.ActionOrigin.Switch_RightBumper -> PromptFontConsts.NINTENDO_RIGHT_SHOULDER
        SteamController.ActionOrigin.Switch_Plus -> PromptFontConsts.NINTENDO_PLUS
        SteamController.ActionOrigin.Switch_Minus -> PromptFontConsts.NINTENDO_MINUS
        SteamController.ActionOrigin.Switch_Capture -> PromptFontConsts.ICON_NINTENDO_SWITCH + PromptFontConsts.SONY_SHARE
        SteamController.ActionOrigin.Switch_LeftTrigger_Pull ->  PromptFontConsts.NINTENDO_LEFT_TRIGGER
        SteamController.ActionOrigin.Switch_LeftTrigger_Click -> PromptFontConsts.NINTENDO_LEFT_TRIGGER
        SteamController.ActionOrigin.Switch_RightTrigger_Pull ->  PromptFontConsts.NINTENDO_RIGHT_TRIGGER
        SteamController.ActionOrigin.Switch_RightTrigger_Click -> PromptFontConsts.NINTENDO_RIGHT_TRIGGER
        SteamController.ActionOrigin.Switch_LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.Switch_LeftStick_Click -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.Switch_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.Switch_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.Switch_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.Switch_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.Switch_RightStick_Move ->  PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.Switch_RightStick_Click -> PromptFontConsts.ANALOG_R_CLICK
        SteamController.ActionOrigin.Switch_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.Switch_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.Switch_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.Switch_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.Switch_DPad_North -> PromptFontConsts.XBOX_DPAD_UP
        SteamController.ActionOrigin.Switch_DPad_South -> PromptFontConsts.XBOX_DPAD_DOWN
        SteamController.ActionOrigin.Switch_DPad_West ->  PromptFontConsts.XBOX_DPAD_LEFT
        SteamController.ActionOrigin.Switch_DPad_East ->  PromptFontConsts.XBOX_DPAD_RIGHT
        SteamController.ActionOrigin.Switch_ProGyro_Move -> "Gyro"
        SteamController.ActionOrigin.Switch_ProGyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.Switch_ProGyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.Switch_ProGyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.Switch_RightGyro_Move -> "RGyro"
        SteamController.ActionOrigin.Switch_RightGyro_Pitch -> "RGyroPitch"
        SteamController.ActionOrigin.Switch_RightGyro_Yaw -> "RGyroYaw"
        SteamController.ActionOrigin.Switch_RightGyro_Roll -> "RGyroRoll"
        SteamController.ActionOrigin.Switch_LeftGyro_Move -> "LGyro"
        SteamController.ActionOrigin.Switch_LeftGyro_Pitch -> "LGyroPitch"
        SteamController.ActionOrigin.Switch_LeftGyro_Yaw -> "LGyroYaw"
        SteamController.ActionOrigin.Switch_LeftGyro_Roll -> "LGyroRoll"
        SteamController.ActionOrigin.Switch_LeftGrip_Lower -> "NS-LG-L"
        SteamController.ActionOrigin.Switch_LeftGrip_Upper -> "NS-LG-U"
        SteamController.ActionOrigin.Switch_RightGrip_Lower -> "NS-RG-L"
        SteamController.ActionOrigin.Switch_RightGrip_Upper -> "NS-RG-U"
        SteamController.ActionOrigin.PS4_DPad_Move -> PromptFontConsts.DPAD
        SteamController.ActionOrigin.XBoxOne_DPad_Move -> PromptFontConsts.XBOX_DPAD
        SteamController.ActionOrigin.XBox360_DPad_Move -> PromptFontConsts.XBOX_DPAD
        SteamController.ActionOrigin.Switch_DPad_Move -> PromptFontConsts.DPAD
        SteamController.ActionOrigin.PS5_X -> PromptFontConsts.SONY_A
        SteamController.ActionOrigin.PS5_Circle -> PromptFontConsts.SONY_B
        SteamController.ActionOrigin.PS5_Triangle -> PromptFontConsts.SONY_Y
        SteamController.ActionOrigin.PS5_Square -> PromptFontConsts.SONY_X
        SteamController.ActionOrigin.PS5_LeftBumper -> PromptFontConsts.SONY_LEFT_SHOULDER
        SteamController.ActionOrigin.PS5_RightBumper -> PromptFontConsts.SONY_RIGHT_SHOULDER
        SteamController.ActionOrigin.PS5_Option -> PromptFontConsts.SONY_DUALSENSE_OPTIONS
        SteamController.ActionOrigin.PS5_Create -> PromptFontConsts.SONY_DUALSENSE_SHARE
        SteamController.ActionOrigin.PS5_Mute -> PromptFontConsts.ICON_SPEAK
        SteamController.ActionOrigin.PS5_LeftPad_Touch -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.PS5_LeftPad_Swipe -> PromptFontConsts.TRACKPAD_L_ANY
        SteamController.ActionOrigin.PS5_LeftPad_Click -> PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.PS5_LeftPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.PS5_LeftPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.PS5_LeftPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.PS5_LeftPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.PS5_RightPad_Touch -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.PS5_RightPad_Swipe -> PromptFontConsts.TRACKPAD_R_ANY
        SteamController.ActionOrigin.PS5_RightPad_Click -> PromptFontConsts.TRACKPAD_R_CLICK
        SteamController.ActionOrigin.PS5_RightPad_DPadNorth -> PromptFontConsts.TRACKPAD_R_UP
        SteamController.ActionOrigin.PS5_RightPad_DPadSouth -> PromptFontConsts.TRACKPAD_R_DOWN
        SteamController.ActionOrigin.PS5_RightPad_DPadWest ->  PromptFontConsts.TRACKPAD_R_LEFT
        SteamController.ActionOrigin.PS5_RightPad_DPadEast ->  PromptFontConsts.TRACKPAD_R_RIGHT
        SteamController.ActionOrigin.PS5_CenterPad_Touch -> PromptFontConsts.SONY_DUALSENSE_TOUCHPAD
        SteamController.ActionOrigin.PS5_CenterPad_Swipe -> PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.MOUSE_ANY
        SteamController.ActionOrigin.PS5_CenterPad_Click -> PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.BUTTON_PRESS
        SteamController.ActionOrigin.PS5_CenterPad_DPadNorth -> PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_UP
        SteamController.ActionOrigin.PS5_CenterPad_DPadSouth -> PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_DOWN
        SteamController.ActionOrigin.PS5_CenterPad_DPadWest ->  PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_LEFT
        SteamController.ActionOrigin.PS5_CenterPad_DPadEast ->  PromptFontConsts.SONY_DUALSENSE_TOUCHPAD + PromptFontConsts.MOUSE_MOVE_RIGHT
        SteamController.ActionOrigin.PS5_LeftTrigger_Pull -> PromptFontConsts.SONY_LEFT_TRIGGER
        SteamController.ActionOrigin.PS5_LeftTrigger_Click -> PromptFontConsts.SONY_LEFT_TRIGGER
        SteamController.ActionOrigin.PS5_RightTrigger_Pull -> PromptFontConsts.SONY_RIGHT_TRIGGER
        SteamController.ActionOrigin.PS5_RightTrigger_Click -> PromptFontConsts.SONY_RIGHT_TRIGGER
        SteamController.ActionOrigin.PS5_LeftStick_Move ->  PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.PS5_LeftStick_Click -> PromptFontConsts.SONY_LEFT_STICK
        SteamController.ActionOrigin.PS5_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.PS5_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.PS5_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.PS5_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.PS5_RightStick_Move ->  PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.PS5_RightStick_Click -> PromptFontConsts.SONY_RIGHT_STICK
        SteamController.ActionOrigin.PS5_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.PS5_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.PS5_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.PS5_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.PS5_DPad_Move -> PromptFontConsts.DPAD
        SteamController.ActionOrigin.PS5_DPad_North -> PromptFontConsts.DPAD_UP
        SteamController.ActionOrigin.PS5_DPad_South -> PromptFontConsts.DPAD_DOWN
        SteamController.ActionOrigin.PS5_DPad_West -> PromptFontConsts.DPAD_LEFT
        SteamController.ActionOrigin.PS5_DPad_East -> PromptFontConsts.DPAD_RIGHT
        SteamController.ActionOrigin.PS5_Gyro_Move -> "Gyro"
        SteamController.ActionOrigin.PS5_Gyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.PS5_Gyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.PS5_Gyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.XBoxOne_LeftGrip_Lower -> "X1-LG-L"
        SteamController.ActionOrigin.XBoxOne_LeftGrip_Upper -> "X1-LG-U"
        SteamController.ActionOrigin.XBoxOne_RightGrip_Lower -> "X1-RG-L"
        SteamController.ActionOrigin.XBoxOne_RightGrip_Upper -> "X1-RG-U"
        SteamController.ActionOrigin.XBoxOne_Share -> PromptFontConsts.SONY_SHARE
        SteamController.ActionOrigin.SteamDeck_A -> PromptFontConsts.XBOX_A
        SteamController.ActionOrigin.SteamDeck_B -> PromptFontConsts.XBOX_B
        SteamController.ActionOrigin.SteamDeck_X -> PromptFontConsts.XBOX_X
        SteamController.ActionOrigin.SteamDeck_Y -> PromptFontConsts.XBOX_Y
        SteamController.ActionOrigin.SteamDeck_L1 -> PromptFontConsts.SONY_LEFT_SHOULDER
        SteamController.ActionOrigin.SteamDeck_R1 -> PromptFontConsts.SONY_RIGHT_SHOULDER
        SteamController.ActionOrigin.SteamDeck_Menu -> PromptFontConsts.XBOX_MENU
        SteamController.ActionOrigin.SteamDeck_View -> PromptFontConsts.XBOX_VIEW
        SteamController.ActionOrigin.SteamDeck_LeftPad_Touch -> PromptFontConsts.TRACKPAD_L_TOUCH
        SteamController.ActionOrigin.SteamDeck_LeftPad_Swipe -> PromptFontConsts.TRACKPAD_L_ANY
        SteamController.ActionOrigin.SteamDeck_LeftPad_Click -> PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.SteamDeck_LeftPad_DPadNorth -> PromptFontConsts.TRACKPAD_L_UP
        SteamController.ActionOrigin.SteamDeck_LeftPad_DPadSouth -> PromptFontConsts.TRACKPAD_L_DOWN
        SteamController.ActionOrigin.SteamDeck_LeftPad_DPadWest ->  PromptFontConsts.TRACKPAD_L_LEFT
        SteamController.ActionOrigin.SteamDeck_LeftPad_DPadEast ->  PromptFontConsts.TRACKPAD_L_RIGHT
        SteamController.ActionOrigin.SteamDeck_RightPad_Touch -> PromptFontConsts.TRACKPAD_R_TOUCH
        SteamController.ActionOrigin.SteamDeck_RightPad_Swipe -> PromptFontConsts.TRACKPAD_R_ANY
        SteamController.ActionOrigin.SteamDeck_RightPad_Click -> PromptFontConsts.TRACKPAD_R_CLICK
        SteamController.ActionOrigin.SteamDeck_RightPad_DPadNorth -> PromptFontConsts.TRACKPAD_R_UP
        SteamController.ActionOrigin.SteamDeck_RightPad_DPadSouth -> PromptFontConsts.TRACKPAD_R_DOWN
        SteamController.ActionOrigin.SteamDeck_RightPad_DPadWest ->  PromptFontConsts.TRACKPAD_R_LEFT
        SteamController.ActionOrigin.SteamDeck_RightPad_DPadEast ->  PromptFontConsts.TRACKPAD_R_RIGHT
        SteamController.ActionOrigin.SteamDeck_L2_SoftPull -> PromptFontConsts.XBOX_LEFT_TRIGGER_PULL
        SteamController.ActionOrigin.SteamDeck_L2 -> PromptFontConsts.SONY_LEFT_TRIGGER
        SteamController.ActionOrigin.SteamDeck_R2_SoftPull -> PromptFontConsts.XBOX_RIGHT_TRIGGER_PULL
        SteamController.ActionOrigin.SteamDeck_R2 -> PromptFontConsts.SONY_RIGHT_TRIGGER
        SteamController.ActionOrigin.SteamDeck_LeftStick_Move -> PromptFontConsts.ANALOG_L
        SteamController.ActionOrigin.SteamDeck_L3 -> PromptFontConsts.ANALOG_L_CLICK
        SteamController.ActionOrigin.SteamDeck_LeftStick_DPadNorth -> PromptFontConsts.ANALOG_L_UP
        SteamController.ActionOrigin.SteamDeck_LeftStick_DPadSouth -> PromptFontConsts.ANALOG_L_DOWN
        SteamController.ActionOrigin.SteamDeck_LeftStick_DPadWest ->  PromptFontConsts.ANALOG_L_LEFT
        SteamController.ActionOrigin.SteamDeck_LeftStick_DPadEast ->  PromptFontConsts.ANALOG_L_RIGHT
        SteamController.ActionOrigin.SteamDeck_LeftStick_Touch -> PromptFontConsts.ANALOG_L_TOUCH
        SteamController.ActionOrigin.SteamDeck_RightStick_Move -> PromptFontConsts.ANALOG_R
        SteamController.ActionOrigin.SteamDeck_R3 -> PromptFontConsts.ANALOG_R_CLICK
        SteamController.ActionOrigin.SteamDeck_RightStick_DPadNorth -> PromptFontConsts.ANALOG_R_UP
        SteamController.ActionOrigin.SteamDeck_RightStick_DPadSouth -> PromptFontConsts.ANALOG_R_DOWN
        SteamController.ActionOrigin.SteamDeck_RightStick_DPadWest ->  PromptFontConsts.ANALOG_R_LEFT
        SteamController.ActionOrigin.SteamDeck_RightStick_DPadEast ->  PromptFontConsts.ANALOG_R_RIGHT
        SteamController.ActionOrigin.SteamDeck_RightStick_Touch -> PromptFontConsts.ANALOG_R_TOUCH
        SteamController.ActionOrigin.SteamDeck_L4 -> PromptFontConsts.GAMEPAD_L4
        SteamController.ActionOrigin.SteamDeck_R4 -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.SteamDeck_L5 -> PromptFontConsts.GAMEPAD_L5
        SteamController.ActionOrigin.SteamDeck_R5 -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.SteamDeck_DPad_Move -> PromptFontConsts.XBOX_DPAD
        SteamController.ActionOrigin.SteamDeck_DPad_North -> PromptFontConsts.XBOX_DPAD_UP
        SteamController.ActionOrigin.SteamDeck_DPad_South -> PromptFontConsts.XBOX_DPAD_DOWN
        SteamController.ActionOrigin.SteamDeck_DPad_West ->  PromptFontConsts.XBOX_DPAD_LEFT
        SteamController.ActionOrigin.SteamDeck_DPad_East ->  PromptFontConsts.XBOX_DPAD_RIGHT
        SteamController.ActionOrigin.SteamDeck_Gyro_Move -> "Gyro"
        SteamController.ActionOrigin.SteamDeck_Gyro_Pitch -> "GyroPitch"
        SteamController.ActionOrigin.SteamDeck_Gyro_Yaw -> "GyroYaw"
        SteamController.ActionOrigin.SteamDeck_Gyro_Roll -> "GyroRoll"
        SteamController.ActionOrigin.SteamDeck_Reserved1 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved2 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved3 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved4 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved5 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved6 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved7 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved8 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved9 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved10 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved11 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved12 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved13 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved14 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved15 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved16 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved17 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved18 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved19 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.SteamDeck_Reserved20 -> PromptFontConsts.ICON_QUESTION
        SteamController.ActionOrigin.Switch_JoyConButton_N -> PromptFontConsts.GAMEPAD_Y
        SteamController.ActionOrigin.Switch_JoyConButton_E -> PromptFontConsts.GAMEPAD_B
        SteamController.ActionOrigin.Switch_JoyConButton_S -> PromptFontConsts.GAMEPAD_A
        SteamController.ActionOrigin.Switch_JoyConButton_W -> PromptFontConsts.GAMEPAD_X
        SteamController.ActionOrigin.PS5_LeftGrip -> PromptFontConsts.GAMEPAD_L4
        SteamController.ActionOrigin.PS5_RightGrip -> PromptFontConsts.GAMEPAD_R4
        SteamController.ActionOrigin.PS5_LeftFn -> PromptFontConsts.KEYBOARD_FN + PromptFontConsts.TRACKPAD_L_CLICK
        SteamController.ActionOrigin.PS5_RightFn -> PromptFontConsts.KEYBOARD_FN + PromptFontConsts.TRACKPAD_R_CLICK
    }
    return SteamActionInputGlyph(this, promptFontText)
}
